// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "skills-react",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api924976bb",
            "endpoint": "https://e7w709nryf.execute-api.us-east-1.amazonaws.com/react",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
